x-veld:
  code:

services:
  veld_transform_wiki_json_to_txt:
    build: .
    volumes:
      - ./src/:/veld/code/:z
    command: python /veld/code/transform_wiki_json_to_txt.py
    environment:
      in_json_folder : null
      out_txt_file: null
      out_data_description: null
      cpu_count: null
      set_split_sentences: null
      sample_size_percentage: 100
      sample_random_seed: null
      info_interval: 100

